version: '3'
services:
  database_mongo:
    container_name: mongo_container
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_DATABASE=imager_mongo_db
    volumes:
      - ./mongodb_data_container:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - imager_net
  backend_spring:
    container_name: spring_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_container
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      database_mongo:
        condition: service_started
    networks:
      - imager_net

networks:
  imager_net:
    driver: bridge
